title: Begoña Perez Rodriguez - 3D artist and designer
description: >
  **I am Begoña**, a 3D artist and designer.
copyright: CreaByBego
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: 
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "begona.perezrodriguez@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
collections:
  sections:
    output: true
    permalink: /:path/
  items:
    output: true
    permalink: /:collection/:path/